"""Tabela

Revision ID: 18ab99499add
Revises: 6d6d16e1811a
Create Date: 2025-11-30 00:38:57.032390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18ab99499add'
down_revision: Union[str, Sequence[str], None] = '6d6d16e1811a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfil_usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_usuario',
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferencias_notificacao', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('perfil_usuario_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('perfil_usuario_pkey'))
    )
    # ### end Alembic commands ###
