"""add tarefa

Revision ID: 6d6d16e1811a
Revises: 0007
Create Date: 2025-11-23 18:30:12.517662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d6d16e1811a'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_usuario_id'), 'tarefa', ['usuario_id'], unique=False)
    op.drop_index(op.f('ix_acao_meta_meta'), table_name='acao_meta')
    op.drop_constraint(op.f('acao_meta_responsavel_id_fkey'), 'acao_meta', type_='foreignkey')
    op.create_foreign_key(None, 'acao_meta', 'usuario', ['responsavel_id'], ['id'])
    op.drop_index(op.f('ix_avaliacao_avaliado'), table_name='avaliacao')
    op.drop_index(op.f('ix_avaliacao_avaliador'), table_name='avaliacao')
    op.drop_constraint(op.f('avaliacao_ciclo_id_fkey'), 'avaliacao', type_='foreignkey')
    op.drop_constraint(op.f('avaliacao_avaliador_id_fkey'), 'avaliacao', type_='foreignkey')
    op.drop_constraint(op.f('avaliacao_avaliado_id_fkey'), 'avaliacao', type_='foreignkey')
    op.create_foreign_key(None, 'avaliacao', 'ciclo_avaliacao', ['ciclo_id'], ['id'])
    op.create_foreign_key(None, 'avaliacao', 'usuario', ['avaliado_id'], ['id'])
    op.create_foreign_key(None, 'avaliacao', 'usuario', ['avaliador_id'], ['id'])
    op.alter_column('ciclo_avaliacao', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ciclo_avaliacao_nome'), table_name='ciclo_avaliacao')
    op.alter_column('equipe', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_equipe_nome'), table_name='equipe')
    op.drop_index(op.f('ix_feedback_de_usuario'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_para_usuario'), table_name='feedback')
    op.drop_constraint(op.f('feedback_para_usuario_id_fkey'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('feedback_de_usuario_id_fkey'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('feedback_avaliacao_id_fkey'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'usuario', ['para_usuario_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'usuario', ['de_usuario_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'avaliacao', ['avaliacao_id'], ['id'])
    op.drop_index(op.f('ix_item_avaliacao_avaliacao'), table_name='item_avaliacao')
    op.drop_index(op.f('ix_item_avaliacao_avaliacao_id'), table_name='item_avaliacao')
    op.drop_constraint(op.f('item_avaliacao_competencia_id_fkey'), 'item_avaliacao', type_='foreignkey')
    op.create_foreign_key(None, 'item_avaliacao', 'usuario_competencia', ['competencia_id'], ['id'])
    op.drop_index(op.f('ix_meta_ciclo'), table_name='meta')
    op.drop_index(op.f('ix_meta_usuario'), table_name='meta')
    op.drop_constraint(op.f('meta_ciclo_id_fkey'), 'meta', type_='foreignkey')
    op.drop_constraint(op.f('meta_pdi_id_fkey'), 'meta', type_='foreignkey')
    op.drop_constraint(op.f('meta_usuario_id_fkey'), 'meta', type_='foreignkey')
    op.create_foreign_key(None, 'meta', 'pdi', ['pdi_id'], ['id'])
    op.create_foreign_key(None, 'meta', 'ciclo_avaliacao', ['ciclo_id'], ['id'])
    op.create_foreign_key(None, 'meta', 'usuario', ['usuario_id'], ['id'])
    op.alter_column('papel', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_papel_nome'), table_name='papel')
    op.drop_index(op.f('ix_pdi_usuario'), table_name='pdi')
    op.drop_constraint(op.f('pdi_usuario_id_fkey'), 'pdi', type_='foreignkey')
    op.drop_constraint(op.f('pdi_ciclo_id_fkey'), 'pdi', type_='foreignkey')
    op.create_foreign_key(None, 'pdi', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'pdi', 'ciclo_avaliacao', ['ciclo_id'], ['id'])
    op.alter_column('perfil_usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('perfil_usuario_usuario_id_fkey'), 'perfil_usuario', type_='foreignkey')
    op.create_foreign_key(None, 'perfil_usuario', 'usuario', ['usuario_id'], ['id'])
    op.alter_column('usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_usuario_email'), 'usuario', type_='unique')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.alter_column('usuario_competencia', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_usuario_competencia_nome'), table_name='usuario_competencia')
    op.drop_index(op.f('ix_usuario_competencia_usuario'), table_name='usuario_competencia')
    op.drop_index(op.f('ix_usuario_papel_papel'), table_name='usuario_papel')
    op.drop_index(op.f('ix_usuario_papel_usuario'), table_name='usuario_papel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usuario_papel_usuario'), 'usuario_papel', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_usuario_papel_papel'), 'usuario_papel', ['papel_id'], unique=False)
    op.create_index(op.f('ix_usuario_competencia_usuario'), 'usuario_competencia', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_usuario_competencia_nome'), 'usuario_competencia', ['nome'], unique=False)
    op.alter_column('usuario_competencia', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_usuario_email'), 'usuario', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('usuario', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'perfil_usuario', type_='foreignkey')
    op.create_foreign_key(op.f('perfil_usuario_usuario_id_fkey'), 'perfil_usuario', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('perfil_usuario', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'pdi', type_='foreignkey')
    op.drop_constraint(None, 'pdi', type_='foreignkey')
    op.create_foreign_key(op.f('pdi_ciclo_id_fkey'), 'pdi', 'ciclo_avaliacao', ['ciclo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('pdi_usuario_id_fkey'), 'pdi', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pdi_usuario'), 'pdi', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_papel_nome'), 'papel', ['nome'], unique=False)
    op.alter_column('papel', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'meta', type_='foreignkey')
    op.drop_constraint(None, 'meta', type_='foreignkey')
    op.drop_constraint(None, 'meta', type_='foreignkey')
    op.create_foreign_key(op.f('meta_usuario_id_fkey'), 'meta', 'usuario', ['usuario_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('meta_pdi_id_fkey'), 'meta', 'pdi', ['pdi_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('meta_ciclo_id_fkey'), 'meta', 'ciclo_avaliacao', ['ciclo_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_meta_usuario'), 'meta', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_meta_ciclo'), 'meta', ['ciclo_id'], unique=False)
    op.drop_constraint(None, 'item_avaliacao', type_='foreignkey')
    op.create_foreign_key(op.f('item_avaliacao_competencia_id_fkey'), 'item_avaliacao', 'usuario_competencia', ['competencia_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_item_avaliacao_avaliacao_id'), 'item_avaliacao', ['avaliacao_id'], unique=False)
    op.create_index(op.f('ix_item_avaliacao_avaliacao'), 'item_avaliacao', ['avaliacao_id'], unique=False)
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_avaliacao_id_fkey'), 'feedback', 'avaliacao', ['avaliacao_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('feedback_de_usuario_id_fkey'), 'feedback', 'usuario', ['de_usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('feedback_para_usuario_id_fkey'), 'feedback', 'usuario', ['para_usuario_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_feedback_para_usuario'), 'feedback', ['para_usuario_id'], unique=False)
    op.create_index(op.f('ix_feedback_de_usuario'), 'feedback', ['de_usuario_id'], unique=False)
    op.create_index(op.f('ix_equipe_nome'), 'equipe', ['nome'], unique=False)
    op.alter_column('equipe', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ciclo_avaliacao_nome'), 'ciclo_avaliacao', ['nome'], unique=False)
    op.alter_column('ciclo_avaliacao', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.create_foreign_key(op.f('avaliacao_avaliado_id_fkey'), 'avaliacao', 'usuario', ['avaliado_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('avaliacao_avaliador_id_fkey'), 'avaliacao', 'usuario', ['avaliador_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('avaliacao_ciclo_id_fkey'), 'avaliacao', 'ciclo_avaliacao', ['ciclo_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_avaliacao_avaliador'), 'avaliacao', ['avaliador_id'], unique=False)
    op.create_index(op.f('ix_avaliacao_avaliado'), 'avaliacao', ['avaliado_id'], unique=False)
    op.drop_constraint(None, 'acao_meta', type_='foreignkey')
    op.create_foreign_key(op.f('acao_meta_responsavel_id_fkey'), 'acao_meta', 'usuario', ['responsavel_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_acao_meta_meta'), 'acao_meta', ['meta_id'], unique=False)
    op.drop_index(op.f('ix_tarefa_usuario_id'), table_name='tarefa')
    op.drop_table('tarefa')
    # ### end Alembic commands ###
